// 场景数据：由剧本自动生成，可直接修改台词
// t: chapter 章节 / bg 背景 / say 台词(dialogue 对话, mono 内心独白) / narr 旁白 / dream 梦境占位 / overlay 插入图 / clearOverlay 撤插入图 / black 黑屏 / special 待定标记 / choice 选项 / muxu 木须生长动画 / video 视频（播完定格） / date 日期浮现
window.SCENES = [
{"t": "chapter", "name": "序"},
{"t": "dream", "n": 1},
{"t": "bg", "name": "客厅", "folder": "序"},
{"t": "say", "who": "白水", "text": "小游！小游！小——游——出来——", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你怎么来了！", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "我来找你玩呢！我刚刚敲了好久的门！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我开门了没见到你人呀！", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "你从来没开过门呀！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我刚刚明明……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "我问了阿姨，她说你一直在房间里呢，可能是睡着了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我……我睡着了吗？我还以为……难道那些都是梦吗？", "kind": "mono"},
{"t": "say", "who": "白水", "text": "小游，我们走吧！快出去玩儿！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "也许真的是梦。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我得和妈妈说一声。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "妈——我和白水出去玩！", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "好，去吧，记得回来吃饭。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "好！", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "你们注意安全啊！不要去废屋！！", "kind": "dialogue"},
{"t": "say", "who": "小游、白水", "text": "知道啦！", "kind": "dialogue"},
{"t": "bg", "name": "街道冰棒", "folder": "序"},
{"t": "say", "who": "白水", "text": "冰棒，好好吃啊！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "肚子都凉凉的。", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "哇！！！我的冰棒在融化！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "要滴下来了！", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "哦哦哦！看我的！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水手上的冰棒化得很快，糖水流到了他的手肘处。他伸着舌头想要去舔，却怎么够也够不到，表情拧在一起，很搞笑。", "kind": "mono"},
{"t": "say", "who": "白水", "text": "诶，我舌头好酸。算了！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "黏黏的……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "超级啊！晚上回去再洗手吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "好脏啊。", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "不管啦！哇——小游你看——", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "夕阳好漂亮啊。", "kind": "dialogue"},
{"t": "bg", "name": "黄昏树", "folder": "序"},
{"t": "say", "who": "小游", "text": "白水说的对。这是夏天，日落姗姗来迟，橘色和粉色混在一起勾得细细长长。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "好漂亮。", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "小游，我们去哪里吧！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "什么……？", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "就是那里啊，废屋那里。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不太好吧……大人说不要去的……妈妈刚刚也说……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "去看看吧！去看看有什么呢？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水拖着我往前，我有些害怕，但最终没有拒绝。废屋究竟有什么呢，也许我也是想知道的。", "kind": "mono"},
{"t": "bg", "name": "神树前（幼年）", "folder": "序"},
{"t": "say", "who": "白水", "text": "你看，废屋离我们也没多远嘛，平时总觉得很远呢。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "毕竟是镇子的最深处。", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "好——现在我们要进去喽！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "等……", "kind": "dialogue"},
{"t": "video", "name": "倒下视频", "folder": "序"},
{"t": "black"},
{"t": "say", "who": "小游", "text": "这就是我那天的所有记忆——白水的鲜血把我的记忆都覆盖了。", "kind": "mono"},
{"t": "chapter", "name": "第一章"},
{"t": "black"},
{"t": "bg", "name": "教室图1", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "什么嘛，居然又在课上睡着了。今天一定早睡。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "手好痒……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "手上被咬了个包……蚊子吗？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "喂，三三！", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "干嘛？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "是不是有蚊子啊？", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "可能吧，夏天了。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "你别老影响我，赶紧听课吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "切，真是好学生……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "好痒。这老师在讲什么啊？什么的人？欧迈拉斯，什么鬼……", "kind": "dialogue"},
{"t": "bg", "name": "楼道图", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "啊，终于下课了。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "你上课根本也不累吧，我看你在睡觉。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不小心就睡着了。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "昨天又熬夜干嘛？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "哈哈，什么都没干啊。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "那你每天总是睡眠不够的样子？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我睡眠不好啦。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "你压力不要老是这么大。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我没有……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我总是做梦……梦……", "kind": "mono"},
{"t": "say", "who": "三三", "text": "好吧，你自己休息好。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我知道。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "……喂，你会离开吗？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "啊？你在说什么？", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "就是刚刚上课讲的那个。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我被蚊子咬得好痒。老师刚刚讲了什么？", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "《离开欧迈拉斯的人》。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "就是一个很幸福的城镇，最后发现所有的幸福都是建立在一个孩子的痛苦上的，因此有人选择了离开，不过也有人选择留下。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "小游，你会选择离开还是留下？", "kind": "dialogue"},
{"t": "choice", "options": [{"text": "我不知道。", "active": true}, {"text": "留下。", "active": false}, {"text": "离开。", "active": false}]},
{"t": "say", "who": "三三", "text": "哦……你不知道。好吧，其实我也不知道。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "三三翻了翻身上，递过来一个小瓶子。", "kind": "mono"},
{"t": "say", "who": "三三", "text": "喏，你喷一喷吧，别抓了。", "kind": "dialogue"},
{"t": "bg", "name": "有外套版本", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "妈妈，我觉得我需要喷一点杀虫剂在身上。", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "如果你想要自杀的话随便你喷吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "但是我被蚊子叮的地方好痒。我恨蚊子。", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "我看看。", "kind": "dialogue"},
{"t": "bg", "name": "袖子卷起来版本", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "妈妈拿着我的手臂看了好半天。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "已经一个星期了，我被咬了好多包，身上都有。", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "你以前也这么招蚊子？不会是过敏了吧？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不知道啊，这些包很痒很痛，而且越来越大越来越肿了。", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "好像是有点严重，你抹药没？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我喷了点同桌给我的花露水。", "kind": "dialogue"},
{"t": "say", "who": "妈妈", "text": "死小孩，你喷花露水有什么用？一会儿吃点药，我再找点红花油给你抹吧，你等下。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "哦。", "kind": "dialogue"},
{"t": "bg", "name": "插入红花油图片", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "妈妈给我涂了红花油。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "红花油融化在蚊子包上，油油的，味道很刺鼻。", "kind": "mono"},
{"t": "bg", "name": "教室图2", "folder": "第一章节"},
{"t": "say", "who": "三三", "text": "小游，你抹了什么？好臭。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "红花油。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "你这些蚊子包怎么还没好？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不知道啊。唉……我感觉越来越肿了，而且有时候会很痛。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "是不是发炎了啊？你别老穿长袖捂着。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "搞不懂。我身上都有好多，感觉要被蚊子吞掉了……", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "你是不是被蜘蛛咬了，中毒了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "天，真的假的。那也太恐怖了。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "真的吧……你看你啊这个好严重，感觉都半个月了。会不会蜘蛛都在里面生宝宝了，这么肿……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "呕，好恶心。你不要再说了。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "到时候医生把你这个包切开发现里面有好多小蜘蛛。天啊。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我要打死你……不准再讲。", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "好吧。我还觉得你得去医院吧……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "上课了。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "什么鬼……不会真的是蜘蛛吧。怎么感觉身体里有东西在动……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我是不是疯了……都怪三三乱讲。", "kind": "mono"},
{"t": "bg", "name": "教室图3", "folder": "第一章节"},
{"t": "say", "who": "小游", "text": "好痒……再抓一下。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "好痒……好痒……好痒……好痒……好痒……好痒……好痒……", "kind": "dialogue"},
{"t": "muxu"},
{"t": "say", "who": "小游", "text": "什么东西啊啊啊啊啊啊啊啊啊！！！！", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我……！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我失去了意识。", "kind": "mono"},
{"t": "say", "who": "三三", "text": "老师！小游晕倒了！", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "小游？！小游？！", "kind": "dialogue"},
{"t": "say", "who": "三三", "text": "去医院！老师，小游要去医院！", "kind": "dialogue"},
{"t": "chapter", "name": "第二章"},
{"t": "bg", "name": "医院前台", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "姐姐，你好。", "kind": "dialogue"},
{"t": "say", "who": "护士", "text": "小朋友，你有什么事？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "姐姐，我想问一下有个叫白水的病人，他在哪个房间？", "kind": "dialogue"},
{"t": "say", "who": "护士", "text": "白水……？你等我找一下。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "好的，就是那个吐血的小男孩。麻烦姐姐了。", "kind": "dialogue"},
{"t": "say", "who": "护士", "text": "我记得他，白水……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他在哪里？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "在白水晕倒后，我再也没见过他。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "他被大人们带走了，大概病情很重，我们不被允许探望。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我很担心他。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "镇子上只有这一家医院，他应该就在这里吧。", "kind": "mono"},
{"t": "say", "who": "护士", "text": "白水……啊，找到了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他在哪？", "kind": "dialogue"},
{"t": "say", "who": "护士", "text": "小朋友，白水已经出院了哦。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "出院？这怎么可能呢？！", "kind": "dialogue"},
{"t": "say", "who": "护士", "text": "你自己看，你看，白水已经在三天前出院了。", "kind": "dialogue"},
{"t": "bg", "name": "登记簿显示", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "护士递过来的登记信息上确实写着白水的出院日期。可是……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水，你去哪里了？", "kind": "mono"},
{"t": "bg", "name": "白水家门前", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "白水！白水？！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "没人开门……", "kind": "mono"},
{"t": "bg", "name": "白水家门前2", "folder": "第二章节"},
{"t": "say", "who": "王叔", "text": "小游，你不要敲了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "王叔……白水去哪里了？！", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水晕倒那天我好像也看见了王叔，或许他会知道白水的去向。", "kind": "mono"},
{"t": "say", "who": "王叔", "text": "他前两天从医院回来，好像就跟他妈妈走了哦，不知道去哪里。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "怎……怎么可能？！他没跟我讲啊！", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "人家自己家里的事嘛，做什么要跟你讲。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不是，他他他，他跟我，我们关系很好的！", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "哦哟，小朋友就是这样的啦。牵肠挂肚的哦。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我只是很担心他……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "王叔，我只想知道白水去了哪里。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "说这些……白水已经离开这个镇子啦，你不要再找了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "为什么离开……他为什么走？", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "这些我都不晓得啦，这个镇子就是这样的嘛，来来往往的人……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "可是……", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "游啊，叔走了啊。至于白水，你也不要再找了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "王叔走了，我没得到任何答案，只能离开了白水家。", "kind": "mono"},
{"t": "bg", "name": "白水家门前", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "白水真的走了吗？他那天吐了很多血，已经没事了吗？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水是我小时候搬到小镇来认识的第一个小孩。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "他和他的妈妈一起生活，就像我一样。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我们一直是彼此最好的朋友。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水是身体很健康的小孩，直到那天在废屋前晕倒……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "妈妈说的没错，如果那天我们没有偷偷跑去那里就好了……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "可是白水就算要走，为什么不和我告别呢……唉……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水真的走了吗？我不信……再去一次医院吧！", "kind": "mono"},
{"t": "dream", "n": 2},
{"t": "bg", "name": "病房1", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "好痛……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "好痛……身上好痛，怎么会这样……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "这是哪里……窗外……废屋？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "这是什么地方，我在哪里……好像在课上晕倒了，三三呢……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "身上……什么东西长出来了。", "kind": "mono"},
{"t": "bg", "name": "病房2", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "……谁？", "kind": "dialogue"},
{"t": "bg", "name": "病房3", "folder": "第二章节"},
{"t": "bg", "name": "病房4", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "一个男人进来了。是很陌生的面孔，我没有在镇子里见过他。", "kind": "mono"},
{"t": "say", "who": "胡中", "text": "看来你醒了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你是谁？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "你没必要知道。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我妈妈……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "放心，你目前很安全。你妈妈知道你在这里。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你要做什么？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "我什么也不做。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "这里究竟是哪里？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "很难说清楚。你只要知道你要在这里待上一段时间就好。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "为什么？我……我怎么了……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "这个陌生的男人掀开了我的被子，好像有什么缠绕着我。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "但是一阵剧痛袭来，我什么也没看清……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我听见那个男人的声音，他在说什么……？", "kind": "mono"},
{"t": "say", "who": "胡中", "text": "哇，你要死了。", "kind": "dialogue"},
{"t": "black"},
{"t": "bg", "name": "病房5", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "好痛……已经x月x日了……", "kind": "mono"},
{"t": "bg", "name": "病房6", "folder": "第二章节"},
{"t": "say", "who": "胡中", "text": "很痛？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "是昨天那个男人，他坐在了我床边的一把椅子上。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "你究竟是谁……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "一个外乡人。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "那你……啊！", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我想问点什么，可以一瞬间仿佛有什么东西刺破了我的皮肉。", "kind": "mono"},
{"t": "say", "who": "胡中", "text": "疼是正常的。也许以后你会和这个疼痛相伴很久。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你昨天说，我要死了。我是被蜘蛛咬了吗？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "蜘蛛？你倒是会想。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不是蜘蛛，那是什么？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "是比蜘蛛可怕上一万倍的东西。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "可是我还不想死。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "你说了不算啊。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你能救我吗？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "我……？我救你？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "什么意思？难道我没救了吗。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "真可怜，这一切本不该由你经历。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "那为什么……？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "我也没办法。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你到底在说什么……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "男人的每个回应都让我感到好奇怪，他是谁，带我来这里做什么，我通通不知道。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我想问得更多，但是男人没有给我这个机会", "kind": "mono"},
{"t": "say", "who": "胡中", "text": "明天见。", "kind": "dialogue"},
{"t": "bg", "name": "病房7", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "他走了，我还有很多东西没有明白。比如我身上这些……", "kind": "mono"},
{"t": "bg", "name": "病房8", "folder": "第二章节"},
{"t": "date", "text": "9月11日"},
{"t": "say", "who": "小游", "text": "比如我身上这些木根……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "是木根吗，我不知道，看起来像某种植物的根须。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "为什么……这些东西会从我的身体里长出来。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "而且好痛……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我听见的这些声音……究竟是谁的声音……好痛……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "是谁的声音……？昨天那个男人还没来吗？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "有人在窗外吗？", "kind": "mono"},
{"t": "bg", "name": "病房1", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "我吃力地坐起身，想要看看窗外，然而那里什么都没有。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "除了……远处的废屋。", "kind": "mono"},
{"t": "bg", "name": "病房8", "folder": "第二章节"},
{"t": "date", "text": "9月12日"},
{"t": "bg", "name": "病房9", "folder": "第二章节"},
{"t": "bg", "name": "病房6", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "你来了……你昨天怎么没来。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "有事。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "感觉怎么样？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "能好到哪里？你看我……我现在就是个怪物。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "对。你现在是个怪物。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我只是一个学生，我还要上学，我还要高考……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "也许吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "为什么会变成现在这个样子？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我想回家。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "回家让你妈妈看到你现在这样？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你们怎么跟我妈妈解释的？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "你妈妈会理解的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不可能……妈妈……我想回家……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "睡吧，睡一觉就好了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他站了起来，是又要离开了吗？", "kind": "mono"},
{"t": "bg", "name": "病房9", "folder": "第二章节"},
{"t": "say", "who": "胡中", "text": "你妈妈知道你平安。", "kind": "dialogue"},
{"t": "bg", "name": "病房10", "folder": "第二章节"},
{"t": "bg", "name": "病房11", "folder": "第二章节"},
{"t": "bg", "name": "病房12", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "你又来了……怎么每次都来得很匆忙。", "kind": "dialogue"},
{"t": "bg", "name": "病房6", "folder": "第二章节"},
{"t": "say", "who": "胡中", "text": "我有我的事。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "那我呢？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "你？你的命运很直白，不用我操心吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "就是变成一个怪物？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "怪物？如果你这么想的话，那就怪物吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我每天都很疼。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "想来也是。小游，你以后想做什么？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我不知道……我还没想好。我本来想去省城上大学。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "挺好的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我是不是再也去不了了？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "也许吧。也许能去，也许不能去……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你去过省城吗？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "去过。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "什么时候？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "离开镇子的那一年……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你以前也是镇子上的？你……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "嘘。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "男人打断了我的话，看起来他不想向我展示任何一点他的过往。毕竟我连他的名字都还不知道。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "你……你叫什么？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "胡中。我叫胡中。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "胡中……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "胡中，你知道吗，我觉得也许我是被这棵树诅咒了，这棵神树。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "为什么这么想？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你看我身上这些，像不像树上的木根？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "……小游。你是被选中的孩子。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "被选中？被谁选中？这棵树吗？", "kind": "dialogue"},
{"t": "video", "name": "病房视频", "folder": "第二章节"},
{"t": "date", "text": "9月13日"},
{"t": "say", "who": "乌鸦", "text": "你是被那个孩子选中的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "谁？被谁？你怎么会说话？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "还是来了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "什么来了？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "我曾经见过你……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我？我没见过你。镇子里没有你这样的鸟。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "当然。那些鸟来来去去，从来不在镇子里停留。啊，除了那只鸟是吗？它在你的手里死了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你……你怎么会知道。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "秋天的时候，镇子里有许许多多这样的鸟，它们从很远的地方来，要到别的地方去。很多鸟没能抵达目的地，中途死了，死在镇子里。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我和白水曾经捡到过一只这样的鸟，几个星期以来我们一直喂养它，试图打破某一种魔咒。", "kind": "mono"},
{"t": "overlay", "name": "正中插入图", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "但是……毫无疑问，我们失败了。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我们太笨了，不明白太多的吃食喂入这只鸟的口中它是会被撑死。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我们太想爱它，太想让它好起来……最后竟然把它撑死了。好可笑……", "kind": "mono"},
{"t": "clearOverlay"},
{"t": "say", "who": "小游", "text": "可是，可是这只鸟……为什么会知道这一切呢？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我已经不再养任何的鸟了……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "别担心，小游，那不是你的错。那只鸟会死去的，那是它的命运。就像……现在的你的命运一样。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我的命运……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "小游，你还记得白水吗。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水……我不会忘记他……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "当然。他也没有忘记你。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他回来了吗？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "他从来没离开。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "可是、可是、", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "小游，你想不想见白水？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我……我不知道。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "也许是因为今天再次提及那只已经死去的鸟，夜里我梦见了它。", "kind": "mono"},
{"t": "dream", "n": 3},
{"t": "bg", "name": "病房14", "folder": "第二章节"},
{"t": "date", "text": "9月14日"},
{"t": "say", "who": "小游", "text": "你昨天问我，想不想见白水。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "你想好了吗？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我想好了。白水……我想见见他！", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "那我会告诉你他……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他在哪里？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "我会告诉你他、他们的所有故事……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "那一天也是一样的，很黑很黑的夜里。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你是说……白水。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "不，不是白水。那个人比白水的存在要早上许多许多。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "是谁。", "kind": "dialogue"},
{"t": "overlay", "name": "图画1", "folder": "第二章节"},
{"t": "say", "who": "乌鸦", "text": "希望镇的神是很早以前就存在的……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "神……", "kind": "dialogue"},
{"t": "overlay", "name": "图画2", "folder": "第二章节"},
{"t": "say", "who": "乌鸦", "text": "镇子里的人曾经犯过很多罪孽。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "犯罪？什么？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "太久远的事情。人们以为罪孽可以如此轻易地被遗忘，甚至后来他们自己也忘了。", "kind": "dialogue"},
{"t": "overlay", "name": "图画3", "folder": "第二章节"},
{"t": "say", "who": "乌鸦", "text": "但是上天目睹了一切，祂降下天罚，人们五脏六腑出血，痛苦把整个镇子填满。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "然后呢。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "然后神出现了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "神？希望镇的神？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "是的。那神是镇守这一方土地的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我从未见过。", "kind": "dialogue"},
{"t": "overlay", "name": "图画4", "folder": "第二章节"},
{"t": "say", "who": "乌鸦", "text": "你如今已经见不到。那时候，他说，这镇子所有的罪由我来承担。只惩戒我一人，镇子的后辈将会得救。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他……为什么要这样做。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "没有人知道。也许他觉得旁观亦是一种罪。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "上天答应了吗。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "最终答应了。那一天大雨，血被冲洗干净，人们好起来了。唯独废屋那里没有降下雨水。", "kind": "dialogue"},
{"t": "overlay", "name": "图画5", "folder": "第二章节"},
{"t": "say", "who": "乌鸦", "text": "神被囚禁在那里，和神树融为一体。从此每一个生命降临，新的木根就从他体内生长，神要承担镇上每个生命的喜怒哀乐。", "kind": "mono"},
{"t": "clearOverlay"},
{"t": "bg", "name": "病房14", "folder": "第二章节"},
{"t": "say", "who": "小游", "text": "……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "但神被囚禁的时候，他的妻子已经怀了孩子。暴雨那天，孩子出生了。一个人的惩戒，变成了一条血脉的惩戒。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "白氏。一代一代，每一个白氏，都走完了同样的路。他们没有选择。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水他……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "他八岁就触碰到了他的命运。旧神提前死去，新神提前降临。小小的白水，提早肩负起了他不该承受的一切。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他那时候才八岁……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "镇子里的人把他关起来。就像关住他的父辈一样。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他们怎么可以…！", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "他们忘记了。出去之后在太阳下摇摇晃晃，背地里的事不约而同地被忘掉了。人都是这样的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你怎么知道这些事的？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "我曾经遇见过最初的神。他随手将我救下，也许是他的神力存留。我成为了白氏的一部分，听见他们所不能说，明白他们所不能想。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "……知道这件事的人有多少？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "那些老人，在将要老去的时候就会把这个秘密告诉他们的孩子。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他们的孩子也……", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "是的。就像白氏背负的诅咒不会断一样。这样一个看守神明的秘密军团也不会消失。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "那现在……？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "没有子嗣的神，生命的最后竟然只有你的存在是如此清晰的。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水他难道……", "kind": "dialogue"},
{"t": "dream", "n": 4},
{"t": "say", "who": "小游", "text": "这是我常常梦见的白水……", "kind": "mono"},
{"t": "chapter", "name": "第三章"},
{"t": "bg", "name": "病房图", "folder": "第三章节"},
{"t": "bg", "name": "病房图2", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "王叔。", "kind": "dialogue"},
{"t": "bg", "name": "病房图3", "folder": "第三章节"},
{"t": "say", "who": "王叔", "text": "小游，没想到这件事会和你有牵连。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "那时候我去找过白水，你告诉我，他已经离开了。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "他确实已经离开了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "不，他是被你们带走了。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "我们不得不带走他。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你们明明可以不！你们明明可以放过他……明明可以的！", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "你……要恨就恨白家的那个孩子吧。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "为什么……为什么要这样对白水。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我变成这样……", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "都是那孩子的错。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你们凭什么！凭什么这么说！", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "唉，你不能明白。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "只是你将要接替他，在这个世界上你还有什么事想做，最后的日子里你可以尽管提要求。", "kind": "dialogue"},
{"t": "choice", "options": [{"text": "……带我去见见白水吧。", "active": true}, {"text": "我想要你们受到应有的惩罚", "active": false}]},
{"t": "say", "who": "胡中", "text": "你决定了？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "嗯。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "你跟我来吧。他要死了，也许你很快也要替代他。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你带路。", "kind": "dialogue"},
{"t": "bg", "name": "街道", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "王叔带我走向废屋，这条路我曾经走过。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我很想念白水，我要见白水，我要救出白水。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "除此以外，我什么都不想管了。", "kind": "mono"},
{"t": "bg", "name": "走路", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "这是我第一次进入废屋。王叔带着我穿过一条通道，来到了废屋的地下。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "这里竟然有这么大的一个空间。", "kind": "mono"},
{"t": "bg", "name": "门前", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "我一个人进去。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "这……这……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我说了，我要一个人进去。你走。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "可是……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我不会对他做什么。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我只是想见见他。你走。否则我不知道我会做出什么。", "kind": "dialogue"},
{"t": "say", "who": "王叔", "text": "好……好……小游，你不要冲动。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "王叔走了，这是我从小认识的长辈。如今看见他的脸却只感到恶心。", "kind": "mono"},
{"t": "say", "who": "胡中", "text": "我们也要走？", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你……你们……不用。你们在门口等我吧。我想单独看看白水。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "好。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我一个人走进了房间，一切正如我梦中所见。", "kind": "dialogue"},
{"t": "bg", "name": "白水图", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "白水，白水……这样小的白水，一个人被关在这里。", "kind": "dialogue"},
{"t": "bg", "name": "模糊", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "我贴在玻璃上，冰凉的玻璃，将我的脸变得潮湿。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我以为是里面的水流出来了……不，不是的。这是什么？是我的眼泪吗？", "kind": "dialogue"},
{"t": "bg", "name": "白水图", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "乌鸦飞了进来，落在我的肩上。", "kind": "mono"},
{"t": "say", "who": "乌鸦", "text": "他很虚弱。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我知道……很多年了……这么多的痛苦。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "他在呼唤你。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水？白水在呼唤我吗？", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "是。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "可是我什么也没有听见。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "我听到了。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "他说什么？", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "小……游……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "是你吗，白水。我在这里……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "小游……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我……我要怎么救下你……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "我可以告诉你。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我不知道胡中是什么时候进来的。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "你拿的是什么？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "一把木剑。", "kind": "dialogue"},
{"t": "bg", "name": "插入木剑图", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "一把木剑？用来做什么？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "打碎这块玻璃。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "用这把木剑？", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "对。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "胡中把木剑递给我，出乎意料，这把剑很轻。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "看上去像小卖部会贩卖的儿童玩具。", "kind": "mono"},
{"t": "say", "who": "乌鸦", "text": "小游，你有没有想好。你如今有了打开这玻璃缸的武器，你有没有想好。打碎玻璃只是一瞬间的事，简单地如同呼吸一样。白水会回到地面，这里的人会死去，天罚迟迟地会到来他们身上。", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "小游，这是你自己的选择。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "这选择太沉重了……一个月前，我以为我人生里最大的烦恼只是报考哪所大学。", "kind": "dialogue"},
{"t": "say", "who": "乌鸦", "text": "你个人的命运已经离你而去。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我曾经……我曾经连一只鸟都不曾拯救。为什么在这时刻要将人类的命运交予到我的手中了呢。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "你们走吧……我……我……", "kind": "dialogue"},
{"t": "say", "who": "胡中", "text": "好。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "胡中和乌鸦离开了，只剩下我和白水。", "kind": "mono"},
{"t": "bg", "name": "模糊2", "folder": "第三章节"},
{"t": "say", "who": "白水", "text": "小游，我很想你。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我连一只鸟都不曾拯救过……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "没关系……没关系……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我连一只鸟都不曾拯救过……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "为什么……我要来做这个决定。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水、白水。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水……你会死去吗……", "kind": "mono"},
{"t": "dream", "n": 5},
{"t": "say", "who": "小游", "text": "这一切都是因为白水而存在的。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我无法再忍受了。什么幸福，什么痛苦，我不知道。我只知道，我要……结束这一切。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "木剑很轻，我将剑举过我的头顶。", "kind": "mono"},
{"t": "bg", "name": "砸玻璃", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "玻璃片碎落在地上，发出毁灭一样的声响。水流了出来，在瞬间淹没房间。", "kind": "mono"},
{"t": "bg", "name": "下沉", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "白水去哪里了？怎么这么多水……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "我会被淹死吗？白水也是……我们要死在这个房间的洪水之中了……", "kind": "mono"},
{"t": "say", "who": "小游", "text": "是我亲手造成的。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "到头来，我是不是仍然留不住任何一条生命？", "kind": "mono"},
{"t": "say", "who": "小游", "text": "放弃吧……放弃。放弃是简单的。我不会再拯救任何事物了。命运，随便你要把我带去哪里吧。", "kind": "mono"},
{"t": "say", "who": "白水", "text": "小……小游……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水？", "kind": "dialogue"},
{"t": "bg", "name": "两个人水里", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "比白水更先触碰到我的，是他身上的所有木根。我们两个现在竟然有了相似的怪物形态，好可笑……", "kind": "mono"},
{"t": "say", "who": "白水", "text": "小游。", "kind": "dialogue"},
{"t": "bg", "name": "抱", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "白水抱住了我，我们两个人的血和水和木根混杂在一起。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水，小小的白水，我……我要做什么。", "kind": "mono"},
{"t": "bg", "name": "抱2", "folder": "第三章节"},
{"t": "say", "who": "小游", "text": "我亲手让木剑从腹部贯穿了我们两个人。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "看啊……木根掉落在地上，洪水也开始消退。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "白水，你死去吧，你死去了，诅咒没有去处，无疾而终……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水，对不起。我只能想到这样。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "白水，作为补偿，我愿意陪同你一起死去。", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "死也许竟是这样好的一件事……", "kind": "mono"},
{"t": "say", "who": "白水", "text": "小游……谢谢你。谢谢你救了我，谢谢你愿意陪我死去……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "小游，因为你，死亡于是一点儿也不可怕……对不起，把你扯入这一切……", "kind": "dialogue"},
{"t": "say", "who": "白水", "text": "但是小游，我好高兴……好高兴……我们今时今日是一同死去的……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "嗯……", "kind": "dialogue"},
{"t": "say", "who": "小游", "text": "我和白水的眼睛都闭上了，肩膀上枕着彼此的头颅。", "kind": "mono"},
{"t": "say", "who": "小游", "text": "真好……我、我最终救起了一只鸟……我们……我们都得救了……", "kind": "mono"}
];
