let sideScene,sideSceneEnd,sideExtension,sideWalk=[],sideDirection=1,baishuiRun=[],blue=[],stopTime=.28; const ROUTE=6500, WORLD=8200;
'use strict';
const $=s=>document.querySelector(s), c=$('#world'),g=c.getContext('2d'), W=960,H=540,CX=480,CY=232;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)), smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
const layer=document.createElement('canvas');layer.width=W;layer.height=H;const layerContext=layer.getContext('2d');
let worldKeys=[],heroFrames=[],introTime=0,travel=0,travelEnds=[],travelRate=0,cameraZoom=1;
let ready=false,phase='ready',distance=0,held=false,velocity=0,elapsed=0,endTime=0,clock=0,muted=false,talk=null,spoken=new Set(),sprites=[],plates=[],softPlates=[],streetMesh,actorKeys=[],house,endingArt,gaits=[];
const lines=[['奶奶','小游啊，长这么高了。','你妈妈今天买了排骨哦。'],['阿姨','今天热得很。','晚点会下雨吧。'],['小孩','你要去哪里？','那边没有东西玩的。'],['男人','链子松了，等下就好。','你也要修车？'],['女人','菜市场今天鱼很新鲜。','不过贵了两块。'],['年轻人','……对，我下个月回来。','不好意思啊，借过一下。'],['老人','今年雨水好。','好多年没这么好过了。'],['母亲','他刚睡着，小声一点哦。','乖，不哭了。'],['学生','小游？你怎么在这儿。','我先走了啊，要迟到了。'],['男人','天要黑了。','早点回家吧。']];
// Each person is anchored in the same image coordinates as the architecture.
const placements=[
 [0,0,150,470,160],[1,0,735,420,88],
 [2,0,260,390,64],[3,0,632,365,70],
 [4,0,355,348,70],[5,0,584,335,59],
 [6,0,568,325,33],[7,0,405,317,42],
 [8,0,542,309,39],[9,0,429,302,36]];
const actors=placements.map(([id,stage,x,y,h])=>({id,stage,x,y,h,button:null}));
const img=src=>new Promise((resolve,reject)=>{let a=new Image();a.onload=()=>resolve(a);a.onerror=()=>reject(Error(src));a.src='dream5-assets/'+src});
function cut(image,col,row,cols,rows,magenta=false){let a=document.createElement('canvas');a.width=Math.floor(image.width/cols);const cuts=!magenta&&rows===3?[0,326/1024,689/1024,1]:null;const sy=cuts?image.height*cuts[row]:row*image.height/rows,sh=cuts?image.height*(cuts[row+1]-cuts[row])-2:image.height/rows;a.height=Math.floor(sh);let q=a.getContext('2d',{willReadFrequently:true});q.drawImage(image,col*image.width/cols,sy,image.width/cols,sh,0,0,a.width,a.height);let d=q.getImageData(0,0,a.width,a.height),p=d.data;let queue=[],seen=new Uint8Array(a.width*a.height);const add=i=>{if(i<0||i>=seen.length||seen[i])return;seen[i]=1;let k=i*4,r=p[k],v=p[k+1],b=p[k+2];if(magenta?(r>v*1.4+35&&b>v*1.4+35):(Math.min(r,v,b)>226&&Math.max(r,v,b)-Math.min(r,v,b)<25)){queue.push(i);p[k+3]=0;}};for(let x=0;x<a.width;x++){add(x);add((a.height-1)*a.width+x)}for(let y=0;y<a.height;y++){add(y*a.width);add(y*a.width+a.width-1)}for(let n=0;n<queue.length;n++){let i=queue[n];if(i%a.width)add(i-1);if(i%a.width<a.width-1)add(i+1);add(i-a.width);add(i+a.width)}if(!magenta&&((col===2&&row===1)||(col===3&&row===0)||(col===0&&row===2))){for(let y=Math.floor(a.height*.32);y<a.height;y++)for(let x=0;x<a.width;x++){let k=(y*a.width+x)*4;if(((col===2&&row===1&&y>a.height*.52)||(col===3&&row===0&&x>a.width*.68)||(col===0&&row===2&&y>a.height*.63))&&Math.min(p[k],p[k+1],p[k+2])>190&&Math.max(p[k],p[k+1],p[k+2])-Math.min(p[k],p[k+1],p[k+2])<24)p[k+3]=0;}}if(magenta){for(let y=0;y<a.height;y++)for(let x=0;x<a.width;x++){let k=(y*a.width+x)*4;if(x<3||x>a.width-4||y<3||y>a.height-4||(p[k]>p[k+1]*1.4+35&&p[k+2]>p[k+1]*1.4+35))p[k+3]=0;}}if(!magenta){for(let k=0;k<p.length;k+=4)if(Math.min(p[k],p[k+1],p[k+2])>240&&Math.max(p[k],p[k+1],p[k+2])-Math.min(p[k],p[k+1],p[k+2])<15)p[k+3]=0;}let l=a.width,r=0,t=a.height,b=0;for(let y=0;y<a.height;y++)for(let x=0;x<a.width;x++)if(p[(y*a.width+x)*4+3]){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}q.putImageData(d,0,0);let out=document.createElement('canvas');out.width=r-l+1;out.height=b-t+1;out.getContext('2d').drawImage(a,l,t,out.width,out.height,0,0,out.width,out.height);return out;}
function plate(image,feather){let a=document.createElement('canvas');a.width=1920;a.height=1080;let q=a.getContext('2d');q.filter=image.src.includes('far-approach')?'saturate(.40) contrast(.88) brightness(1.01)':'saturate(.50) contrast(.89) brightness(1.01)';q.drawImage(image,0,0,a.width,a.height);q.filter='none';q.fillStyle='rgba(120,145,130,.055)';q.fillRect(0,0,a.width,a.height);if(feather){q.globalCompositeOperation='destination-in';let grad=q.createLinearGradient(0,0,a.width,0);grad.addColorStop(0,'transparent');grad.addColorStop(.13,'black');grad.addColorStop(.87,'black');grad.addColorStop(1,'transparent');q.fillStyle=grad;q.fillRect(0,0,a.width,a.height);grad=q.createLinearGradient(0,0,0,a.height);grad.addColorStop(0,'transparent');grad.addColorStop(.13,'black');grad.addColorStop(.87,'black');grad.addColorStop(1,'transparent');q.fillStyle=grad;q.fillRect(0,0,a.width,a.height)}return a;}
Promise.all(['side-street.png','side-extension.png','people-alpha-v89.png','blue-whole.png','blue-opposite.png','blue-stop.png','baishui-run-armfix16.png','side-open-ending.png'].map(img)).then(([street,extension,people,...art])=>{
 sideScene=street;sideExtension=featherLeft(extension);sideSceneEnd=featherLeft(art[4]);blue=art.slice(0,3).map(keyBlue);baishuiRun=extractApprovedRun(art[3]);travelRate=170;
 for(let i=0;i<10;i++)sprites.push(alphaCut(people,i%4,Math.floor(i/4)));
 actors.forEach(a=>{const b=document.createElement('button');b.className='person';b.ariaLabel='与'+lines[a.id][0]+'交谈';b.onclick=()=>openTalk(a.id);$('#targets').append(b);a.button=b});ready=true;$('#loading').textContent='街道很长。';$('#start').disabled=false;start();
 const params=new URLSearchParams(location.search),sample=params.get('sample');if(sample!==null){start();distance=clamp(+sample);if(params.get('shot')==='ending'){phase='ending';endTime=+params.get('at')||0;}}if(params.get('test')==='walk'){start();held=true}
}).catch(e=>{$('#loading').textContent='素材没有加载完成，请刷新重试。';console.error(e)});
const soundEvents=new Set();const town=new Audio();town.volume=0;let audioContext,bellPlayed=false,windSource,windGain;const birds=new Audio('dream5-assets/birds.wav');birds.volume=.023;let nextDog=9,nextBird=5;
function ambience(){if(windSource)return;const buffer=audioContext.createBuffer(1,audioContext.sampleRate*8,audioContext.sampleRate),data=buffer.getChannelData(0);let v=0;for(let i=0;i<data.length;i++){v=(v+(Math.random()*2-1)*.015)/1.015;data[i]=v;}windSource=audioContext.createBufferSource();windSource.buffer=buffer;windSource.loop=true;let filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;windGain=audioContext.createGain();windGain.gain.value=muted?0:.12;windSource.connect(filter);filter.connect(windGain);windGain.connect(audioContext.destination);windSource.start()}
const explosion=new Audio('dream5-assets/explosion-real.mp3');explosion.preload='auto';explosion.volume=.32;
function boom(){explosion.currentTime=0;play(explosion)}
const bicycleBell=new Audio('dream5-assets/bicycle-bell-real.mp3');bicycleBell.preload='auto';bicycleBell.volume=.22;
function bell(){bellPassedAt=clock;bicycleBell.volume=.24;bicycleBell.currentTime=0;play(bicycleBell);nextBell=clock+4.8}
const dog=new Audio('dream5-assets/dog-village-real.mp3');dog.preload='auto';dog.volume=.30;
const step=new Audio('dream5-assets/step.wav');step.volume=.08;const impact=new Audio('dream5-assets/impact.ogg');impact.volume=.16;
function play(a){if(!muted)a.play().then(()=>{document.body.dataset.lastSound=a.src.split('/').pop();soundEvents.add(document.body.dataset.lastSound);document.body.dataset.soundEvents=JSON.stringify([...soundEvents])}).catch(()=>{})}function start(){if(!ready)return;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});ambience();prepareDog();nextDog=clock+1.2;nextBell=clock+5;bellPlayed=false;phase='walk';introTime=travel=0;distance=elapsed=endTime=0;spoken.clear();$('#veil').hidden=true;$('#again').hidden=true;if(new URLSearchParams(location.search).get('test')==='manualwalk')held=true;}
function openTalk(id){if(phase!=='walk'||spoken.has(id))return;talk={id,index:1};held=false;velocity=0;$('#speaker').textContent=lines[id][0];$('#line').textContent=lines[id][1];$('#dialog').hidden=false;$('#dialog').focus()}
function nextTalk(){if(!talk)return;if(++talk.index<lines[talk.id].length){$('#line').textContent=lines[talk.id][talk.index]}else{spoken.add(talk.id);talk=null;$('#dialog').hidden=true}}
$('#dialog').onclick=nextTalk;$('#dialog').onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();nextTalk()}};$('#start').onclick=start;$('#again').onclick=()=>location.reload();$('#mute').onclick=()=>{muted=!muted;if(dogGain){dogGain.gain.cancelScheduledValues(audioContext.currentTime);dogGain.gain.value=muted?0:dogLevel;}if(windGain)windGain.gain.value=muted?0:.12;[town,dog,step,impact,birds,bicycleBell,explosion].forEach(a=>a.muted=muted);$('#mute').textContent='声音：'+(muted?'关':'开');if(!muted&&phase!=='ready')audioContext?.resume().catch(()=>{})};
$('#walk').onpointerdown=e=>{if((phase==='walk'||phase==='intro')&&!talk){sideDirection=1;held=true;$('#walk').setPointerCapture(e.pointerId)}};$('#walk').onpointerup=$('#walk').onpointercancel=()=>held=false;$('#left').onpointerdown=e=>{if(phase==='walk'&&!talk){sideDirection=-1;held=true;$('#left').setPointerCapture(e.pointerId)}};$('#left').onpointerup=$('#left').onpointercancel=()=>held=false;window.addEventListener('keydown',e=>{if(['ArrowRight','d','D','ArrowLeft','a','A'].includes(e.key)){e.preventDefault();if(!talk){sideDirection=['ArrowLeft','a','A'].includes(e.key)?-1:1;held=true}}});window.addEventListener('keyup',e=>{if(['ArrowRight','d','D','ArrowLeft','a','A'].includes(e.key))held=false});window.addEventListener('blur',()=>{held=false;velocity=0});document.addEventListener('visibilitychange',()=>{held=false;velocity=0;if(document.hidden){audioContext?.suspend();dog.pause();birds.pause();bicycleBell.pause();explosion.pause()}else if(phase!=='ready'){audioContext?.resume().catch(()=>{});if(phase!=='ready')nextDog=Math.min(nextDog,clock+2);}});
function rigidStreet(){for(const m of streetMesh.meshes){const a=m.matrix,scale=Math.hypot(a[0][0],a[1][0]),tx=a[0][2]+a[0][1]*H/2,ty=a[1][2]+a[1][0]*W/2;m.forward=[];m.backward=[];for(let j=0;j<=streetMesh.rows;j++)for(let i=0;i<=streetMesh.cols;i++){const x=i*W/streetMesh.cols,y=j*H/streetMesh.rows;m.forward.push((scale-1)*x+tx,(scale-1)*y+ty);m.backward.push((x-tx)/scale-x,(y-ty)/scale-y);}}}
function alphaCut(image,col,row){const cuts=[0,326,689,1024],cw=image.width/4,sy=image.height*cuts[row]/1024,ch=image.height*(cuts[row+1]-cuts[row])/1024;let a=document.createElement('canvas');a.width=Math.floor(cw);a.height=Math.floor(ch);const q=a.getContext('2d',{willReadFrequently:true});q.drawImage(image,col*cw,sy,cw,ch,0,0,a.width,a.height);const d=q.getImageData(0,0,a.width,a.height);let l=a.width,r=0,t=a.height,b=0;for(let y=0;y<a.height;y++)for(let x=0;x<a.width;x++){const k=(y*a.width+x)*4;if(d.data[k+3]>12){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}else d.data[k+3]=0;}q.putImageData(d,0,0);const out=document.createElement('canvas');out.width=r-l+1;out.height=b-t+1;out.getContext('2d').drawImage(a,l,t,out.width,out.height,0,0,out.width,out.height);return out;}
function prepareTravel(){travelEnds=[0];for(const m of streetMesh.meshes){const scale=m.matrix?Math.hypot(m.matrix[0][0],m.matrix[1][0]):1.7;travelEnds.push(travelEnds.at(-1)+Math.log(scale));}travelRate=170;}
function advanceWalk(dt){if(!dt)return;distance=clamp(distance+sideDirection*velocity*dt/ROUTE);travel+=Math.abs(velocity*dt);}
function distanceMist(){g.save();const mist=g.createRadialGradient(CX,CY,12,CX,CY,245);mist.addColorStop(0,'rgba(163,175,161,.24)');mist.addColorStop(.45,'rgba(163,175,161,.12)');mist.addColorStop(1,'rgba(163,175,161,0)');g.fillStyle=mist;g.fillRect(0,0,W,H);g.restore();}
function lensHaze(){g.save();const fog=g.createLinearGradient(0,0,0,H);fog.addColorStop(0,'rgba(148,164,151,.035)');fog.addColorStop(.4,'rgba(148,164,151,.085)');fog.addColorStop(1,'rgba(148,164,151,.01)');g.fillStyle=fog;g.fillRect(0,0,W,H);g.restore();}
function softPlate(source){return source}
function displacement(field,x,y){const {cols,rows}=streetMesh;const fx=clamp(x/W)*cols,fy=clamp(y/H)*rows,ix=Math.min(cols-1,Math.floor(fx)),iy=Math.min(rows-1,Math.floor(fy)),tx=fx-ix,ty=fy-iy;let dx=0,dy=0;for(let j=0;j<2;j++)for(let i=0;i<2;i++){const k=((iy+j)*(cols+1)+ix+i)*2,w=(i?tx:1-tx)*(j?ty:1-ty);dx+=field[k]*w;dy+=field[k+1]*w}return {x:x+dx,y:y+dy}}
function prepareActorKeys(){actorKeys=actors.map(a=>{const keys=[];keys[a.stage]={foot:{x:a.x,y:a.y},top:{x:a.x,y:a.y-a.h}};for(let j=a.stage;j<streetMesh.meshes.length;j++)keys[j+1]={foot:displacement(streetMesh.meshes[j].forward,keys[j].foot.x,keys[j].foot.y),top:displacement(streetMesh.meshes[j].forward,keys[j].top.x,keys[j].top.y)};for(let j=a.stage-1;j>=0;j--)keys[j]={foot:displacement(streetMesh.meshes[j].backward,keys[j+1].foot.x,keys[j+1].foot.y),top:displacement(streetMesh.meshes[j].backward,keys[j+1].top.x,keys[j+1].top.y)};return keys})}
function triangle(image,src,dst,alpha,ctx=g){const [a,b,c]=src,[p,q,r]=dst,det=(b.x-a.x)*(c.y-a.y)-(c.x-a.x)*(b.y-a.y);if(Math.abs(det)<.001)return;const A=((q.x-p.x)*(c.y-a.y)-(r.x-p.x)*(b.y-a.y))/det,B=((q.y-p.y)*(c.y-a.y)-(r.y-p.y)*(b.y-a.y))/det,C=((r.x-p.x)*(b.x-a.x)-(q.x-p.x)*(c.x-a.x))/det,D=((r.y-p.y)*(b.x-a.x)-(q.y-p.y)*(c.x-a.x))/det;ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();const mx=(p.x+q.x+r.x)/3,my=(p.y+q.y+r.y)/3;for(let i=0;i<3;i++){const v=dst[i],dx=v.x-mx,dy=v.y-my,l=Math.hypot(dx,dy)||1;const x=v.x+dx/l*.55,y=v.y+dy/l*.55;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.clip();ctx.transform(A,B,C,D,p.x-A*a.x-C*a.y,p.y-B*a.x-D*a.y);ctx.drawImage(image,0,0,W,H);ctx.restore()}
function warped(image,field,t,alpha,reveal=null){if(alpha<.002)return;const sx=1+(field[streetMesh.cols*2]-field[0])*t/W,sy=1+(field[(streetMesh.rows*(streetMesh.cols+1))*2+1]-field[1])*t/H;layerContext.clearRect(0,0,W,H);layerContext.save();layerContext.setTransform(sx,0,0,sy,field[0]*t,field[1]*t);layerContext.drawImage(image,0,0,W,H);layerContext.restore();if(reveal!==null&&reveal<1){layerContext.save();layerContext.globalCompositeOperation='destination-in';const radius=reveal*650,mask=layerContext.createRadialGradient(CX,CY,Math.max(0,radius-22),CX,CY,Math.max(1,radius));mask.addColorStop(0,'#000');mask.addColorStop(1,'transparent');layerContext.fillStyle=mask;layerContext.fillRect(0,0,W,H);layerContext.restore();}g.save();g.globalAlpha=alpha;g.drawImage(layer,0,0);g.restore();}
function stableGait(image){const cw=Math.floor(image.width/8),ch=Math.floor(image.height/2),result=[];for(let row=0;row<2;row++){const cells=[];let l=cw,r=0,t=ch,b=0;for(let col=0;col<8;col++){const a=document.createElement('canvas');a.width=cw;a.height=ch;const q=a.getContext('2d',{willReadFrequently:true});q.drawImage(image,col*image.width/8,row*image.height/2,image.width/8,image.height/2,0,0,cw,ch);const d=q.getImageData(0,0,cw,ch);for(let y=0;y<ch;y++)for(let x=0;x<cw;x++){const i=(y*cw+x)*4,p=d.data;if(x<3||x>cw-4||y<3||y>ch-4||(p[i]>p[i+1]*1.4+35&&p[i+2]>p[i+1]*1.4+35))p[i+3]=0;if(p[i+3]>16){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}}q.putImageData(d,0,0);cells.push(a);}const poses=[];for(const col of [4,0,7,4]){const out=document.createElement('canvas');out.width=r-l+1;out.height=b-t+1;out.getContext('2d').drawImage(cells[col],l,t,out.width,out.height,0,0,out.width,out.height);poses.push(out);}for(const a of poses.slice()){const out=document.createElement('canvas');out.width=a.width;out.height=a.height;const q=out.getContext('2d');q.translate(out.width,0);q.scale(-1,1);q.drawImage(a,0,0);poses.push(out);}result.push(...poses);}return result;}
function prepareWorld(){worldKeys=[{s:1,x:0,y:0}];for(const m of streetMesh.meshes){const scale=1+(m.forward[streetMesh.cols*2]-m.forward[0])/W,p=worldKeys.at(-1);worldKeys.push({s:p.s*scale,x:p.x*scale+m.forward[0],y:p.y*scale+m.forward[1]});}}
function cameraFrame(){const n=Math.min(4,Math.floor(distance*5)),t=clamp(distance*5-n),p=worldKeys[n],q=worldKeys[n+1];return {s:p.s+(q.s-p.s)*t,x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t};}
function streetFeather(source){const a=document.createElement('canvas');a.width=source.width;a.height=source.height;const q=a.getContext('2d');q.drawImage(source,0,0);q.globalCompositeOperation='destination-in';for(const vertical of [false,true]){const extent=vertical?a.height:a.width,mask=q.createLinearGradient(0,0,vertical?0:extent,vertical?extent:0);mask.addColorStop(0,'transparent');mask.addColorStop(.025,'black');mask.addColorStop(.975,'black');mask.addColorStop(1,'transparent');q.fillStyle=mask;q.fillRect(0,0,a.width,a.height);}return a;}
const npcX=[450,1030,1580,2100,2650,3180,3730,4250,4770,5290];
const npcY=[429,427,435,431,430,455,426,430,443,429];
function endTravel(){const t=Math.max(0,endTime-2.2);return t*75+t*t*10}
function cameraX(){return clamp(200+distance*ROUTE+(phase==="ending"?endTravel():0)-360,0,7900-W)}
function background(){const cam=cameraX();g.save();g.filter='saturate(.76)';
// Both plates live in one continuous world; the camera never resets at a join.
for(const [art,x] of [[sideScene,0],[sideExtension,2600],[sideSceneEnd,5200]]){
 g.drawImage(art,x-cam,-260,2700,900);

}
g.restore();
for(const a of actors){const x=npcX[a.id]-cam,h=[145,99,79,100,153,159,100,151,140,165][a.id],y=npcY[a.id];if(x<-150||x>W+150){a.button.hidden=true;continue}const box=sprite(sprites[a.id],x,y,h);const active=phase==='walk'&&Math.abs(npcX[a.id]-(200+distance*ROUTE))<160&&!spoken.has(a.id)&&!talk;a.button.hidden=!active;if(active)Object.assign(a.button.style,{left:box.x/W*100+'%',top:box.y/H*100+'%',width:box.w/W*100+'%',height:box.h/H*100+'%'});if(a.id===8&&!bellPlayed&&phase==='walk'&&Math.abs(npcX[a.id]-(200+distance*ROUTE))<190){bellPlayed=true;bell()}}
}
function keyBlue(im){const q=document.createElement('canvas');q.width=im.width;q.height=im.height;const ctx=q.getContext('2d'),d=(()=>{ctx.drawImage(im,0,0);return ctx.getImageData(0,0,q.width,q.height)})();for(let i=0;i<d.data.length;i+=4){const p=d.data;if(p[i]>p[i+1]*1.5&&p[i+2]>p[i+1]*1.5)p[i+3]=0;else if(p[i]>125&&p[i]>p[i+1]&&p[i+1]>p[i+2]+3){p[i]=Math.min(255,p[i]+8);p[i+1]=Math.min(255,p[i+1]+2);}}ctx.putImageData(d,0,0);return q}
const poses=[[1,93,37,215,447,114.828],[1,462,39,186,445,104.4355],[1,868,39,150,445,82.5207],[1,1222,38,233,446,110.9027],[0,91,539,225,449,104.1983],[0,480,540,146,449,86.0278],[0,883,540,128,449,67.6524],[1,836,539,222,448,114.6149]];
const stops=[[2,124,110,310,754,175.0913],[2,668,110,207,754,104.1154],[2,1151,110,206,754,103.7691]];
function drawBlue(x,y,dt,alpha=1){const moving=phase==='walk'&&velocity>8;if(moving)stopTime=0;else stopTime=Math.min(.28,stopTime+dt);const f=moving?poses[Math.floor(travel/13.5)%8]:stops[Math.min(2,Math.floor(stopTime/.095))], [im,sx,sy,w,h,anchor]=f,k=137/h;g.save();g.globalAlpha=alpha;g.fillStyle='#18261d30';g.beginPath();g.ellipse(x,y,24,4,0,0,Math.PI*2);g.fill();g.translate(x,y);g.scale(sideDirection,1);g.imageSmoothingEnabled=false;g.filter='saturate(1.05) brightness(.99)';g.drawImage(blue[im],sx,sy,w,h,-anchor*k,-137,w*k,137);g.restore()}
function sprite(art,x,y,h,alpha=1){if(alpha<=0)return;let w=h*art.width/art.height;g.save();g.globalAlpha=alpha;g.translate(x,y);g.scale(1,.22);let sh=g.createRadialGradient(0,0,0,0,0,w*.4);sh.addColorStop(0,'#282c2470');sh.addColorStop(1,'#282c2400');g.fillStyle=sh;g.beginPath();g.arc(0,0,w*.4,0,Math.PI*2);g.fill();g.restore();g.save();g.globalAlpha=alpha;g.imageSmoothingEnabled=false;g.imageSmoothingQuality="high";if(sprites.includes(art))g.filter='saturate(.78) brightness(.96)';g.drawImage(art,x-w/2,y-h,w,h);g.restore();return {x:x-w/2,y:y-h,w,h};}
function peopleInScene(stage,view,sceneAlpha){
 const stageT=view.local;
 const k=cameraFrame();const projected=actors.map(a=>({a,x:a.x*k.s+k.x,y:a.y*k.s+k.y,h:a.h*k.s})).sort((a,b)=>a.y-b.y);
 for(const {a,x,y,h} of projected){
 const edge=smooth((Math.min(x,W-x)+30)/110),low=smooth((H+70-y)/110);
 const encounterStage=Math.floor(a.id/2), revealAt=encounterStage===0?-1:encounterStage/5-.17+(a.id%2)*.022;
 const encounterVisibility=encounterStage===0?1:smooth((distance-revealAt)/.11);
 const alpha=encounterVisibility*smooth(((a.id===1||a.id===2||a.id===3||a.id===6?h*1.6:h)-18)/22)*sceneAlpha*edge*low*(phase==='ending'?1-smooth(endTime/1.5):1);
 if(a.id===8&&!bellPlayed&&phase==='walk'&&velocity>.001&&alpha>.5&&h>110){bellPlayed=true;bell()}
 const box=sprite(sprites[a.id],x,y,h,alpha);
 const clickable=phase==='walk'&&h>65&&alpha>.18&&!spoken.has(a.id)&&!talk&&box&&x>0&&x<W&&y<H+30;
 if(a.button.hidden===clickable)a.button.hidden=!clickable;
 if(clickable)Object.assign(a.button.style,{left:box.x/W*100+'%',top:box.y/H*100+'%',width:box.w/W*100+'%',height:box.h/H*100+'%'});
 }
}
const sampleMode=new URLSearchParams(location.search).has('sample');let last=performance.now(),lastStep=0,dogPlayed=false,ended=false;function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(document.hidden||sampleMode)dt=0;if(ready){clock+=dt;if(phase!=='ready'){if(clock>nextDog){villageDog();nextDog=clock+10+Math.random()*5}if(clock>nextBell){bicycleBell.volume=bellPassedAt===null?.055:Math.max(.045,.16*Math.exp(-(clock-bellPassedAt)/12));bicycleBell.currentTime=0;play(bicycleBell);nextBell=clock+7+Math.random()*5}if(clock>nextBird){birds.currentTime=0;play(birds);nextBird=clock+17+Math.random()*8}if(!birds.paused&&birds.currentTime>2.3)birds.pause()}if(phase==='intro'){introTime+=dt;if(introTime>=3.2)phase='walk';}if(phase==='walk'){elapsed+=dt;velocity+=((held&&!talk?travelRate:0)-velocity)*Math.min(1,dt*12);advanceWalk(dt);if(velocity>8&&clock-lastStep>.40){step.currentTime=0;play(step);lastStep=clock}if(distance>=1&&!talk){phase='ending';endTime=0;held=false;velocity=0;$('#walk').disabled=true;$('#left').disabled=true;$('#walk').textContent='没有回应';$('#status').textContent='';}}if(phase==='ending')endTime+=dt;
cameraZoom=1;
g.save();g.translate(CX,CY);g.scale(cameraZoom,cameraZoom);g.translate(-CX,-CY);background();g.restore();distanceMist();
$('#targets').style.transform='translate('+((1-cameraZoom)*CX/W*100)+'%, '+((1-cameraZoom)*CY/H*100)+'%) scale('+cameraZoom+')';$('#targets').style.transformOrigin='0 0';
if(phase==='ready'||phase==='intro'||phase==='walk'){drawBlue(200+distance*ROUTE-cameraX(),455,dt);lensHaze();}
if(phase==='ending'){
 const transform=smooth((endTime-.8)/1.2),run=Math.max(0,endTime-2.2);
 const footY=455,height=133; const endX=200+distance*ROUTE+endTravel()-cameraX();
 const tick=Math.floor(Math.max(0,endTime-2.2)*5.5)%16;
 sideDirection=1;drawBlue(endX,footY,dt,1-transform);drawApprovedRun(baishuiRun[Math.floor(run*24)%16],endX,footY,height,transform);lensHaze();
 if((endTime>.35&&endTime<.43)||(endTime>.85&&endTime<.94)){g.save();g.fillStyle='rgba(182,195,178,.28)';g.fillRect(0,0,W,H);g.drawImage(c,0,155,W,18,7,155,W,18);g.fillStyle='rgba(8,18,13,.48)';for(let y=0;y<H;y+=7)g.fillRect(0,y,W,1);g.restore();}
 if(endTime>2.2&&endTime<9.4&&clock-lastStep>.72){step.currentTime=0;play(step);lastStep=clock}
 if(endTime>=9.4){if(!ended){boom();nextBell=clock+1.4;nextDog=clock+3.4;ended=true}g.fillStyle='#000';g.fillRect(0,0,W,H)}
 if(endTime>=17.4){phase='done';$('#again').hidden=false;finishDreamFive();}
}if(phase==='done'){g.fillStyle='#000';g.fillRect(0,0,W,H)}if(phase==='intro')$('#status').textContent='';if(phase==='walk')$('#status').textContent=talk?'':held?'':'← → 移动 · 点击身边的人交谈';}document.body.dataset.audio=JSON.stringify([bicycleBell,dog,explosion].map(a=>({name:a.src.split('/').pop(),duration:a.duration||0,ready:a.readyState,error:a.error?.code||0})));document.body.dataset.phase=phase;document.body.dataset.progress=distance.toFixed(4);document.body.dataset.spoken=JSON.stringify([...spoken]);document.body.dataset.visible=JSON.stringify(actors.filter(a=>a.button&&!a.button.hidden).map(a=>a.id));requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.dream5State={get ready(){return ready},get phase(){return phase},get distance(){return distance},get elapsed(){return elapsed},get spoken(){return [...spoken]},get talk(){return talk},get visible(){return actors.filter(a=>a.button&&!a.button.hidden).map(a=>a.id)}};

function featherLeft(im){const a=document.createElement("canvas");a.width=im.width;a.height=im.height;const q=a.getContext("2d");q.drawImage(im,0,0);q.globalCompositeOperation="destination-in";const f=q.createLinearGradient(0,0,a.width*100/2700,0);f.addColorStop(0,"transparent");f.addColorStop(1,"black");q.fillStyle=f;q.fillRect(0,0,a.width,a.height);return a}

// Reuse the licensed recording, selecting an audible bark rather than its quiet lead-in.
let nextBell=5,bellPassedAt=null,dogBuffer=null,dogOffset=0,dogLevel=.4,dogGain=null,dogLoading=false;
async function prepareDog(){if(dogLoading)return;dogLoading=true;try{dogBuffer=await audioContext.decodeAudioData(await (await fetch('dream5-assets/dog-village-real.mp3')).arrayBuffer());const data=dogBuffer.getChannelData(0),rate=dogBuffer.sampleRate,hop=Math.floor(rate*.25);let max=0,energies=[];for(let i=0;i<data.length;i+=hop){let sum=0;for(let j=i;j<Math.min(i+hop,data.length);j++)sum+=data[j]*data[j];const e=Math.sqrt(sum/hop);energies.push(e);max=Math.max(max,e)}dogOffset=Math.max(0,energies.findIndex(v=>v>max*.5)*.25-.2);let peak=0,sum=0,n=0;for(let i=Math.floor(dogOffset*rate);i<Math.min(data.length,(dogOffset+4.5)*rate);i++){peak=Math.max(peak,Math.abs(data[i]));sum+=data[i]*data[i];n++}dogLevel=Math.min(5,.7/Math.max(.001,peak),.11/Math.max(.001,Math.sqrt(sum/n)));document.body.dataset.dogClip=JSON.stringify({offset:dogOffset,gain:dogLevel,duration:4.5});}catch(e){dogLoading=false;console.warn('Dog recording decode fallback',e)}}
function villageDog(){if(muted)return;if(!dogBuffer){dog.volume=.55;dog.currentTime=0;play(dog);return}const src=audioContext.createBufferSource();src.buffer=dogBuffer;dogGain=audioContext.createGain();dogGain.gain.value=dogLevel;src.connect(dogGain);dogGain.connect(audioContext.destination);const duration=Math.min(4.5,dogBuffer.duration-dogOffset),now=audioContext.currentTime;dogGain.gain.setValueAtTime(dogLevel,now);dogGain.gain.setValueAtTime(dogLevel,now+duration-.25);dogGain.gain.linearRampToValueAtTime(0,now+duration);src.start(0,dogOffset,duration);src.onended=()=>{src.disconnect()};soundEvents.add('dog-village-real.mp3');document.body.dataset.lastDogAt=clock.toFixed(2);document.body.dataset.soundEvents=JSON.stringify([...soundEvents]);}

function extractApprovedRun(im){const frames=[];const cw=im.width/4,ch=im.height/4;for(let i=0;i<16;i++){const a=document.createElement('canvas');a.width=Math.floor(cw);a.height=Math.floor(ch);const q=a.getContext('2d');q.drawImage(im,i%4*cw,Math.floor(i/4)*ch,cw,ch,0,0,cw,ch);const d=q.getImageData(0,0,a.width,a.height);let sx=0,n=0,top=ch,bottom=0;for(let y=0;y<a.height;y++)for(let x=0;x<a.width;x++){const k=(y*a.width+x)*4,p=d.data;if(p[k]>p[k+1]*1.3+30&&p[k+2]>p[k+1]*1.3+30)p[k+3]=0;if(p[k+3]>220){top=Math.min(top,y);bottom=Math.max(bottom,y);if(y<ch*.49&&Math.max(p[k],p[k+1],p[k+2])<115){sx+=x;n++}}}q.putImageData(d,0,0);frames.push({a,anchor:n?sx/n:cw/2,top,bottom});}return frames;}
function drawApprovedRun(p,x,y,height,alpha=1){const span=Math.max(...baishuiRun.map(a=>a.bottom-a.top)),scale=height/span,base=Math.max(...baishuiRun.map(a=>a.bottom));g.save();g.globalAlpha=alpha;g.fillStyle='#28342c40';g.beginPath();g.ellipse(x,y+2,height*.23,4,0,0,7);g.fill();g.imageSmoothingEnabled=false;g.filter='saturate(.72)';g.drawImage(p.a,x-p.anchor*scale,y-span*scale-p.top*scale,p.a.width*scale,p.a.height*scale);g.restore()}

let storyReturnSent=false;
function finishDreamFive(){
 if(storyReturnSent)return;
 storyReturnSent=true;
 try{if(typeof window.parent.returnToStory==='function'){window.parent.returnToStory();$('#again').hidden=true;return;}}catch(error){console.warn('returnToStory failed',error);}
 window.dispatchEvent(new CustomEvent('dream-ended',{detail:{dream:5}}));
}

// Resume browser audio on the first real interaction after automatic entry.
for(const event of ['pointerdown','keydown'])window.addEventListener(event,()=>{if(audioContext)audioContext.resume().catch(()=>{});},{once:true});
